// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: links.sql

package db

import (
	"context"
)

const countLinks = `-- name: CountLinks :one
SELECT COUNT(*)
FROM links
`

func (q *Queries) CountLinks(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLinks)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLink = `-- name: CreateLink :one
INSERT INTO links (
    original_url,
    short_name
)
VALUES (
    $1,
    $2
)
RETURNING
    id,
    original_url,
    short_name,
    created_at
`

type CreateLinkParams struct {
	OriginalUrl string
	ShortName   string
}

func (q *Queries) CreateLink(ctx context.Context, arg CreateLinkParams) (Link, error) {
	row := q.db.QueryRowContext(ctx, createLink, arg.OriginalUrl, arg.ShortName)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ShortName,
		&i.CreatedAt,
	)
	return i, err
}

const deleteLink = `-- name: DeleteLink :execrows
DELETE FROM links
WHERE id = $1
`

func (q *Queries) DeleteLink(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteLink, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getLinkByID = `-- name: GetLinkByID :one
SELECT
    id,
    original_url,
    short_name,
    created_at
FROM links
WHERE id = $1
`

func (q *Queries) GetLinkByID(ctx context.Context, id int64) (Link, error) {
	row := q.db.QueryRowContext(ctx, getLinkByID, id)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ShortName,
		&i.CreatedAt,
	)
	return i, err
}

const listLinks = `-- name: ListLinks :many
SELECT
    id,
    original_url,
    short_name,
    created_at
FROM links
ORDER BY id DESC
LIMIT $1 OFFSET $2
`

type ListLinksParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListLinks(ctx context.Context, arg ListLinksParams) ([]Link, error) {
	rows, err := q.db.QueryContext(ctx, listLinks, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Link
	for rows.Next() {
		var i Link
		if err := rows.Scan(
			&i.ID,
			&i.OriginalUrl,
			&i.ShortName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLink = `-- name: UpdateLink :one
UPDATE links
SET
    original_url = $2,
    short_name = $3
WHERE id = $1
RETURNING
    id,
    original_url,
    short_name,
    created_at
`

type UpdateLinkParams struct {
	ID          int64
	OriginalUrl string
	ShortName   string
}

func (q *Queries) UpdateLink(ctx context.Context, arg UpdateLinkParams) (Link, error) {
	row := q.db.QueryRowContext(ctx, updateLink, arg.ID, arg.OriginalUrl, arg.ShortName)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ShortName,
		&i.CreatedAt,
	)
	return i, err
}
